version: '3'
services:
        redis:
                image: redis
                networks:
                        - lab3
        nodeapp:
                build: ./devops-docker-nodeapp
                depends_on:
                        - redis
                networks:
                        - lab3
                environment:
                        - REDIS_HOST=redis
                        - REDIS_PORT=6379
                        - DEBUG=true
        frontend:
                build: ./devops-docker-frontend
                depends_on:
                        - nodeapp
                ports:
                        - "8081:80"
                networks:
                        - lab3
networks:
        lab3:

